### ISSUE TITLE
make error

### ISSUE THREAD

**Issue by Aryayay** [lmb-freiburg/demon#30]
tensorflow-gpu 1.0.0
python 3.5
...
All the libs satisfied with the requirements specified in readme.
But got errors in the make step.

'demon/lmbspecialops/src/decode_lz4_op.cc:43:29: error: ‘class tensorflow::shape_inference::InferenceContext’ has no member named ‘MakeShapeFromPartialTensorShape’
       TF_RETURN_IF_ERROR(c->MakeShapeFromPartialTensorShape(expected_shape, &out));'

**Comment by benjaminum** [comment]
The dependencies for the lmbspecialops library have changed.
The missing member was introduced after tensorflow 1.0.0.

Building lmbspecialops should work with tensorflow 1.3 or later.

I will update the documentation soon.
